name: Build and Deploy
on:
  push:
    branches:
      - docs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
